"""Cows And Bulls.

Create a program that will play the "cows
and bulls" game with the user. The game
works like this:
    - Randomly generate a 4-digit number.
    - Ask the user to guess a 4-digit
      number.
    - For every digit that the user
      guessed correctly in the correct
      place, they have a "cow."
    - For every digit the user guessed
      correctly in the wrong place is a
      "bull."
    - Every time the user makes a guess,
      tell them how many "cows" and
      "bulls" they have.
    - Once the user guesses the correct
      number, the game is over.
    - Keep track of the number of guesses
      the user makes throughout the game
      and tell the user at the end.

Say the number generated by the computer
is 1038. An example interaction could look
like this:

```python
Welcome to the Cows and Bulls Game! 
Enter a number: 
>>> 1234
2 cows, 0 bulls
>>> 1256
1 cow, 1 bull
...
```

Until the user guesses the number.
"""
from random import randint

def get_cows_and_bulls(
    a_number,
    b_number,
):
    """Get cows and bulls between two strings."""
    a_string = str(a_number)
    b_string = str(b_number)

    cows, bulls = 0, 0
    for ai in range(len(a_string)):
        an = a_string[ai]
        bn = b_string[ai]
        
        if an == bn:
            bulls += 1
        elif an in b_string:
            cows += 1
        else:
            pass

    return cows, bulls


print("Welcome to the Cows and Bulls Game!")

number = randint(1000, 10000)
total_guesses = 0

while True:
    stdin = int(input("Input Guess: "))
    if len(str(stdin)) != 4:
        print("Guess must be a 4-digit number.")
        continue

    cows, bulls = get_cows_and_bulls(stdin, number)
    total_guesses += 1

    print(f"Cows {cows}, Bulls {bulls}")
    if bulls == 4:
        print(f"Took you {total_guesses} to get that.")
        exit()